### ISSUE TITLE
Add support for rust autocomplete and hover

### ISSUE THREAD

**Issue by ConnorJennison** [dotenv-org/dotenv-vscode#47]

**Comment by olivier-fs** [comment]
Hi!

+1 for Rust support !

Rust APIs that need intellisense are in the standard crate (package) std::env :
- std::env::var()
- std::env::set_var()
- std::env::var_os()
- std::env::args()
- std::env::args_os()

The _os() variants return an Option instead of Result.

May be the args API are overkill here, except if you want visual difference between parent process env vars and command line env vars ; in Rust we use a lot e.g 
RUST_LOG=debug myprocess [args]
RUST_BACKTRACE=1 myprocess [args]

**Comment by motdotla** [comment]
Hi @olivier-fs - this was just published to the Microsoft Marketplace. Reinstall and see if it is working well for you.

**Comment by olivier-fs** [comment]
Nice!
Now hovering std::env::var displays the value of the variable.

But it's actually only displaying when writing code.
When debugging with rust-analyzer, no hover info is displayed (I'm running rust stable 1.64.0 with VSCodium 1.72.2.22289 on Windows 10 with your 0.19.0 release).
May be some context info must be handled here to have both extensions play nice together ?

Also, there is a var_os() API, which does not check for valid UTF-8 and returns an Option instead of a Result.
Most people will use var() but you might consider adding hovering info for var_os() too (should be nearly the same thing you've already done for var()).

**Comment by ConnorJennison** [comment]
Hey @olivier-fs 

I don't program in Rust so just to make sure I understand correctly with what I looked up, `std::env::var` and `std::env::var_os` are essentially the same except for `var_os` version just returns `None` if the variable isn't set, whereas `var` returns `Err `. If so yeah that should be easy I should be able to add early next week.

**Comment by olivier-fs** [comment]
You're right!

Option<T> is a standard base type in Rust.
For any type T, Option<T> has value either Some(T) or None.
(Idea copied on Haskell "Either"... Much better than say testing for NULL or nullptr_t in C/C++)

So for var_os() you just have to check for Option returning Some(value), where in var() you had to test for Ok(value).

Hope I'm clear here, tell me if not.
